// ---------------------------------------
// Try... catch
// Якщо виклик функції може завершитися помилкою, рекомендується обернути його блоком try...catch.

// const runCode = () => {
//    console.log('Step 1')
//    try {
//       getData()
//    } catch (error) {
//       console.error(error)
//    }
//    console.log('Step 2')
// }
// ---------------------------------------
// Замикання - це можливість,функції яка знаходиться всередині іншої,отримувати доступ до змінних,які знаходятьсяв області бачення батьківської функції,навіть,якщо батьківська функція вже виконала свою роботу. 

